#CI de nivel 04 - Disparo dos testes dentro do pipe de dev

name: 'Execuçao Integrada'

on:
  workflow_dispatch:

jobs:
  inpecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Checando padronização do código
        run: yarn lint

  unidade:
    runs-on: ubutun-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Executando testes de unidade
        run: yarn test

  e2e-tests:
    runs-on: ubutun-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Executando Testes E2E
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{!cancelled()}}
        with:
          name: report
          path: ./playwright-report

  deploy:
    runs-on: ubutun-latest

    steps:
      - name: Simulação do Deploy
        run: echo "simulando o deploy com sucesso"
